[package]
name = "gemlab"
version = "1.0.1"
edition = "2021"
license = "MIT"
description = "Geometry and meshes laboratory for finite element analyses"
homepage = "https://github.com/cpmech/gemlab"
repository = "https://github.com/cpmech/gemlab"
documentation = "https://docs.rs/gemlab"
readme = "README.md"
categories = ["mathematics", "science"]
keywords = ["geometry", "mesh", "fem"]

[dependencies]
plotpy = "0.6"
russell_lab = "1.2"
russell_sparse = "1.2"
russell_stat = "1.2"
russell_tensor = "1.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tritet = "0.4"

[dev-dependencies]
criterion = "0.5"
