[package]
name = "gemlab"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Geometry laboratory for finite element analyses"
homepage = "https://github.com/cpmech/gemlab"
repository = "https://github.com/cpmech/gemlab"
documentation = "https://docs.rs/gemlab"
readme = "README.md"
categories = ["mathematics", "science"]
keywords = ["geometry", "mesh", "fem"]

[dependencies]
plotpy = { path = "../plotpy", version = "0.2" }
russell_chk = "0.2"
russell_lab = { path = "../russell/russell_lab", version = "0.2" }
russell_sparse = { path = "../russell/russell_sparse", version = "0.2" }
russell_tensor = { path = "../russell/russell_tensor", version = "0.1" }
rmp-serde = "1.0.0"
serde = { version = "1.0.136", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.78"
