[package]
name = "gemlab"
version = "0.6.0"
edition = "2021"
license = "MIT"
description = "Geometry and meshes laboratory for finite element analyses"
homepage = "https://github.com/cpmech/gemlab"
repository = "https://github.com/cpmech/gemlab"
documentation = "https://docs.rs/gemlab"
readme = "README.md"
categories = ["mathematics", "science"]
keywords = ["geometry", "mesh", "fem"]

[dependencies]
plotpy = "0.5"
russell_lab = { path = "../russell/russell_lab", version = "0.6" }
russell_sparse = { path = "../russell/russell_sparse", version = "0.6" }
russell_stat = { path = "../russell/russell_stat", version = "0.6" }
russell_tensor = { path = "../russell/russell_tensor", version = "0.6" }
rmp-serde = "1.1"
serde = { version = "1.0", features = ["derive"] }
tritet = "0.3"

[dev-dependencies]
criterion = "0.5"
serde_json = "1.0"
