use super::{num_divisions, SQRT_2, SQRT_3};
use crate::geometry::{point_circle_distance, point_cylinder_distance, point_line_distance, point_point_distance};
use crate::StrError;
use plotpy::{Canvas, Curve, Plot, Text};
use std::collections::{HashMap, HashSet};
use std::fmt;

/// Default GridSearch number of divisions for all directions
pub const GS_DEFAULT_NDIV: usize = 20;

/// Default GridSearch tolerance for all directions
pub const GS_DEFAULT_TOL: f64 = 1e-4;

/// Specifies the key of containers (or bins in the grid)
type ContainerKey = usize;

/// Specifies the identification number of items
type ItemID = usize;

/// Defines the container type: ID to Coordinates
///
/// Note: we cannot use a HashSet here, because we need to store the coordinates
/// for later use such as when calculating point-to-point distances
type Container = HashMap<ItemID, Vec<f64>>;

/// Defines the containers type: Key to Container
type Containers = HashMap<ContainerKey, Container>;

/// Implements a grid for fast searching entries by coordinates
///
/// # Definitions
///
/// * `xmin` -- (ndim) minimum coordinates to define the boundary
/// * `xmax` -- (ndim) maximum coordinates to define the boundary
/// * `expansion` -- expansion factor for the bounding box.
///     - This constant serves to accommodate eventual imprecision near the boundaries.
///     - The value is a multiplier for `xdelta = xmax - xmin`
///     - For example, **(recommended) expansion = 0.01** means 1% of delta
/// * `ndiv` -- number of division for the longest direction
/// * `tolerance` -- tolerance used to define the Halo and to compare points
///     - For example, tolerance = 1e-4
///
/// **Important:** The number of divisions cannot be very large because it could
/// make the container's `side_length` be smaller the the `tolerance`. Conversely,
/// the tolerance cannot be too large making the halo bigger than the container.
/// In fact, the following constraint must be satisfied:
///
/// ```text
/// side_length = (xmax - xmin) / ndiv > 2·tolerance
/// ```
///
/// # Reference
///
/// * Durand, Farias, and Pedroso (2015) Computing intersections between
///   non-compatible curves and finite elements, Computational Mechanics;
///   DOI=10.1007/s00466-015-1181-y
///
/// # Examples
///
/// ```
/// use gemlab::util::{GridSearch, SQRT_2};
/// use gemlab::StrError;
///
/// fn main() -> Result<(), StrError> {
///     let xmin = &[0.0, 0.0];
///     let xmax = &[10.0, 10.0];
///     let mut grid = GridSearch::new(xmin, xmax, 0.01, Some(2), None)?;
///     grid.insert(123, &[5.5, SQRT_2])?;
///     assert_eq!(grid.find(&[5.5, SQRT_2])?, Some(123));
///     assert_eq!(grid.find(&[5.501, SQRT_2])?, None);
///     if false {
///         grid.draw()?.set_equal_axes(true).save("/tmp/gemlab/doc_grid_search.svg")?;
///     }
///     Ok(())
/// }
/// ```
///
/// ![Output of the code above](https://github.com/cpmech/gemlab/raw/main/data/figures/doc_grid_search.svg)
///
/// The figure above illustrates the grid generated by the example.
pub struct GridSearch {
    ndim: usize,             // space dimension
    ndiv: Vec<usize>,        // (ndim) number of divisions along each direction
    xmin: Vec<f64>,          // (ndim) min values
    xmax: Vec<f64>,          // (ndim) max values
    side_length: Vec<f64>,   // (ndim) side lengths of each container
    coefficient: Vec<usize>, // (3) coefficients [1, ndiv[0], ndiv[0]*ndiv[1]] (Eq. 8)
    tolerance: f64,          // tolerance to define the halo
    tol_dist: f64,           // tolerance to find points using the distance between points
    radius: f64,             // radius of the circumscribed circle of containers
    halo: Vec<Vec<f64>>,     // (ncorner) 4 in 2D or 8 in 3D (each contains ndim coords)
    halo_ncorner: usize,     // number of halo corners = 4 in 2D or 8 in 3D
    containers: Containers,  // structure to hold all items
}

impl GridSearch {
    /// Creates a new GridSearch
    ///
    /// # Input
    ///
    /// * `xmin` -- (ndim) minimum coordinates to define the boundary
    /// * `xmax` -- (ndim) maximum coordinates to define the boundary
    /// * `expansion` -- expansion factor for the bounding box.
    ///     - This constant serves to accommodate eventual imprecision near the boundaries.
    ///     - The value is a multiplier for `xdelta = xmax - xmin`
    ///     - For example, **(recommended) expansion = 0.01** means 1% of delta
    /// * `ndiv` -- number of division (≥ 1)
    ///     - This number is used for the longest direction
    ///     - The other directions will be subdivided with a number such that the
    ///       containers will be square/cubic
    ///     - For the other directions, the minimum number of divisions will be 1,
    ///       in case they are too short compared with the longest direction
    /// * `tolerance` -- tolerance used to define the Halo and to compare points
    ///     - For example, tolerance = 1e-4
    ///
    /// Given the ndiv for the longest direction, the number of divisions for
    /// the other directions are calculated as follows:
    ///
    /// ```text
    /// ndiv_other = truncate((delta_other/delta_long) * ndiv)
    /// ndiv_other = max(1, ndiv_other)
    /// ```
    ///
    /// Thus the resulting grid will be square/cubic
    ///
    /// **Important:** The number of divisions cannot be very large because it could
    /// make the container's `side_length` be smaller the the `tolerance`. Conversely,
    /// the tolerance cannot be too large making the halo bigger than the container.
    /// In fact, the following constraint must be satisfied:
    ///
    /// ```text
    /// side_length = (xmax - xmin) / ndiv > 2·tolerance
    /// ```
    pub fn new(
        xmin: &[f64],
        xmax: &[f64],
        expansion: f64,
        ndiv: Option<usize>,
        tolerance: Option<f64>,
    ) -> Result<Self, StrError> {
        // check input
        let ndim = xmin.len();
        if ndim < 2 || ndim > 3 {
            return Err("min.len() = ndim must be 2 or 3");
        }
        if xmax.len() != ndim {
            return Err("max.len() must equal ndim = min.len()");
        }

        // ndiv
        let ndiv_long = match ndiv {
            Some(v) => v,
            None => GS_DEFAULT_NDIV,
        };
        let ndiv = num_divisions(1, ndiv_long, xmin, xmax)?;
        let coefficient = vec![1, ndiv[0], ndiv[0] * ndiv[1]];

        // tol
        let tolerance = match tolerance {
            Some(v) => v,
            None => GS_DEFAULT_TOL,
        };

        // expanded borders
        let mut xmin = xmin.to_vec();
        let mut xmax = xmax.to_vec();
        if expansion > 0.0 {
            for i in 0..ndim {
                let delta = xmax[i] - xmin[i];
                xmin[i] -= expansion * delta;
                xmax[i] += expansion * delta;
            }
        }

        // check and compute sizes
        let mut xdelta = vec![0.0; ndim];
        let mut side_length = vec![0.0; ndim];
        let mut radius = 0.0;
        for i in 0..ndim {
            xdelta[i] = xmax[i] - xmin[i];
            if xdelta[i] <= 0.0 {
                return Err("xmax must be greater than xmin");
            }
            side_length[i] = xdelta[i] / (ndiv[i] as f64);
            if side_length[i] <= 2.0 * tolerance {
                return Err("container size = (max-min)/ndiv must be > 2·tol; reduce ndiv or tol");
            }
            radius += side_length[i] * side_length[i] / 4.0;
        }
        radius = f64::sqrt(radius);

        // tolerance to find points
        let tol_dist = if ndim == 2 {
            SQRT_2 * tolerance
        } else {
            SQRT_3 * tolerance
        };

        // halo
        let halo_ncorner = usize::pow(2, ndim as u32);
        let halo = vec![vec![0.0; ndim]; halo_ncorner];

        // done
        Ok(GridSearch {
            ndim,
            ndiv,
            xmin,
            xmax,
            side_length,
            coefficient,
            tolerance,
            tol_dist,
            radius,
            halo,
            halo_ncorner,
            containers: HashMap::new(),
        })
    }

    /// Returns whether a point is outside the grid or not (thus we cannot use insert or find)
    ///
    /// # Panics
    ///
    /// This function requires that `x.len() = ndim`, otherwise a panic occurs.
    pub fn is_outside(&self, x: &[f64]) -> bool {
        assert_eq!(x.len(), self.ndim);
        for i in 0..self.ndim {
            if x[i] < self.xmin[i] || x[i] > self.xmax[i] {
                return true;
            }
        }
        return false;
    }

    /// Inserts a new item to a container in the grid
    ///
    /// # Input
    ///
    /// * `id` -- identification number of the item
    /// * `x` -- (ndim) coordinates of the item
    pub fn insert(&mut self, id: usize, x: &[f64]) -> Result<(), StrError> {
        // check
        if x.len() != self.ndim {
            return Err("x.len() must equal ndim");
        }

        // find the key of the container where the coordinates fall in
        let key = match self.calc_container_key(x) {
            Some(k) => k,
            None => return Err("cannot insert point because its coordinates are outside the grid"),
        };

        // add point to container
        self.update_or_insert(key, id, x);

        // add point to the containers touched by the halo corners
        self.set_halo(x);
        let mut tmp = vec![0.0; self.ndim];
        for c in 0..self.halo_ncorner {
            tmp.copy_from_slice(&self.halo[c][0..self.ndim]);
            if let Some(key_corner) = self.calc_container_key(&tmp) {
                if key_corner != key {
                    self.update_or_insert(key_corner, id, x); // make sure to use original `x`
                }
            }
        }
        Ok(())
    }

    /// Finds item
    ///
    /// # Input
    ///
    /// * `x` -- (ndim) coordinates of the item
    ///
    /// # Output
    ///
    /// * `id` -- if found, returns the ID, otherwise, returns None (not found)
    pub fn find(&self, x: &[f64]) -> Result<Option<usize>, StrError> {
        // check
        if x.len() != self.ndim {
            return Err("x.len() must equal ndim");
        }

        // find the key of the container where the coordinates fall in
        let key = match self.calc_container_key(x) {
            Some(k) => k,
            None => return Err("cannot find point because the coordinates are outside the grid"),
        };

        // get the container that has a point near `x`
        let container = match self.containers.get(&key) {
            Some(c) => c,
            None => return Ok(None), // no container has a point near `x`
        };

        // find the closest point to `x` among all points in the container
        for (id, x_other) in container {
            let distance = point_point_distance(x_other, x)?;
            if distance <= self.tol_dist {
                return Ok(Some(*id));
            }
        }
        Ok(None)
    }

    /// Finds points on a 2D or 3D line
    ///
    /// # Input
    ///
    /// * `a` -- (ndim) first point on the line
    /// * `b` -- (ndim) second point on the line (different than `a`)
    ///
    /// # Output
    ///
    /// Returns the ids of points.
    pub fn find_on_line(&self, a: &[f64], b: &[f64]) -> Result<HashSet<usize>, StrError> {
        // check
        if a.len() != self.ndim {
            return Err("a.len() must equal ndim");
        }
        if b.len() != self.ndim {
            return Err("b.len() must equal ndim");
        }

        // find containers near the line
        let nearest_containers = self.containers_near_line(a, b)?;

        // find container points near the line
        let mut ids = HashSet::new();
        for index in nearest_containers {
            let container = self.containers.get(&index).unwrap();
            for (id, x_other) in container {
                let distance = point_line_distance(a, b, x_other)?;
                if distance <= self.tol_dist {
                    ids.insert(id.clone());
                }
            }
        }
        Ok(ids)
    }

    /// Finds points on the perimeter of a circle (2D only)
    ///
    /// # Input
    ///
    /// `center` -- 2D circle center
    /// `radius` -- circle radius
    ///
    /// # Output
    ///
    /// Returns the ids of points.
    ///
    /// # Note
    ///
    /// This works in 2D only.
    pub fn find_on_circle(&self, center: &[f64], radius: f64) -> Result<HashSet<usize>, StrError> {
        // check
        if self.ndim != 2 {
            return Err("this works in 2D only");
        }
        if center.len() != self.ndim {
            return Err("center.len() must equal ndim");
        }

        // find containers near the circle
        let nearest_containers = self.containers_near_circle(center, radius)?;

        // find container points near the circle
        let mut ids = HashSet::new();
        for index in nearest_containers {
            let container = self.containers.get(&index).unwrap();
            for (id, x_other) in container {
                let distance = point_circle_distance(center, radius, x_other)?;
                if f64::abs(distance) <= self.tol_dist {
                    ids.insert(id.clone());
                }
            }
        }
        Ok(ids)
    }

    /// Finds points on the surface of a cylinder (3D only)
    ///
    /// # Input
    ///
    /// `a` -- 3D point on the cylinder axis
    /// `b` -- 3D point on the cylinder axis
    /// `radius` -- cylinder radius
    ///
    /// # Output
    ///
    /// Returns the ids of points.
    ///
    /// # Note
    ///
    /// This works in 3D only.
    pub fn find_on_cylinder(&self, a: &[f64], b: &[f64], radius: f64) -> Result<HashSet<usize>, StrError> {
        // check
        if self.ndim != 3 {
            return Err("this works in 3D only");
        }
        if a.len() != self.ndim {
            return Err("a.len() must equal ndim");
        }
        if b.len() != self.ndim {
            return Err("b.len() must equal ndim");
        }

        // find containers near the cylinder
        let nearest_containers = self.containers_near_cylinder(a, b, radius)?;

        // find container points near the cylinder
        let mut ids = HashSet::new();
        for index in nearest_containers {
            let container = self.containers.get(&index).unwrap();
            for (id, x_other) in container {
                let distance = point_cylinder_distance(a, b, radius, x_other)?;
                if f64::abs(distance) <= self.tol_dist {
                    ids.insert(id.clone());
                }
            }
        }
        Ok(ids)
    }

    /// Find points on the x-y plane (3D only)
    ///
    /// # Input
    ///
    /// `z` -- the plane passes through `z`
    ///
    /// # Output
    ///
    /// Returns the ids of points.
    ///
    /// # Note
    ///
    /// This works in 3D only.
    pub fn find_on_plane_xy(&self, z: f64) -> Result<HashSet<usize>, StrError> {
        // check
        if self.ndim != 3 {
            return Err("this works in 3D only");
        }

        // find containers near the plane
        let nearest_containers = self.containers_near_plane(2, z);

        // find container points near the plane
        let mut ids = HashSet::new();
        for index in nearest_containers {
            let container = self.containers.get(&index).unwrap();
            for (id, x_other) in container {
                let distance = f64::abs(x_other[2] - z);
                if f64::abs(distance) <= self.tol_dist {
                    ids.insert(id.clone());
                }
            }
        }
        Ok(ids)
    }

    /// Find points on the y-z plane (3D only)
    ///
    /// # Input
    ///
    /// `x` -- the plane passes through `x`
    ///
    /// # Output
    ///
    /// Returns the ids of points.
    ///
    /// # Note
    ///
    /// This works in 3D only.
    pub fn find_on_plane_yz(&self, x: f64) -> Result<HashSet<usize>, StrError> {
        // check
        if self.ndim != 3 {
            return Err("this works in 3D only");
        }

        // find containers near the plane
        let nearest_containers = self.containers_near_plane(0, x);

        // find container points near the plane
        let mut ids = HashSet::new();
        for index in nearest_containers {
            let container = self.containers.get(&index).unwrap();
            for (id, x_other) in container {
                let distance = f64::abs(x_other[0] - x);
                if f64::abs(distance) <= self.tol_dist {
                    ids.insert(id.clone());
                }
            }
        }
        Ok(ids)
    }

    /// Find points on the x-z plane (3D only)
    ///
    /// # Input
    ///
    /// `y` -- the plane passes through `y`
    ///
    /// # Output
    ///
    /// Returns the ids of points.
    ///
    /// # Note
    ///
    /// This works in 3D only.
    pub fn find_on_plane_xz(&self, y: f64) -> Result<HashSet<usize>, StrError> {
        // check
        if self.ndim != 3 {
            return Err("this works in 3D only");
        }

        // find containers near the plane
        let nearest_containers = self.containers_near_plane(1, y);

        // find container points near the plane
        let mut ids = HashSet::new();
        for index in nearest_containers {
            let container = self.containers.get(&index).unwrap();
            for (id, x_other) in container {
                let distance = f64::abs(x_other[1] - y);
                if f64::abs(distance) <= self.tol_dist {
                    ids.insert(id.clone());
                }
            }
        }
        Ok(ids)
    }

    /// Draws grid and items
    pub fn draw(&self) -> Result<Plot, StrError> {
        // create plot
        let mut plot = Plot::new();

        // draw grid
        let mut xmin = vec![0.0; self.ndim];
        let mut xmax = vec![0.0; self.ndim];
        let mut ndiv = vec![0; self.ndim];
        for i in 0..self.ndim {
            xmin[i] = self.xmin[i];
            xmax[i] = self.xmax[i];
            ndiv[i] = self.ndiv[i];
        }
        let mut canvas = Canvas::new();
        canvas
            .set_alt_text_color("#5d5d5d")
            .draw_grid(&xmin, &xmax, &ndiv, false, true)?;
        plot.add(&canvas);

        // draw items
        let mut curve = Curve::new();
        let mut text = Text::new();
        curve
            .set_marker_style("o")
            .set_marker_color("#fab32faa")
            .set_marker_line_color("black")
            .set_marker_line_width(0.5);
        text.set_color("#cd0000");
        for container in self.containers.values() {
            for (id, x) in container {
                let txt = format!("{}", id);
                if self.ndim == 2 {
                    curve.draw(&[x[0]], &[x[1]]);
                    text.draw(x[0], x[1], &txt);
                } else {
                    curve.draw_3d(&[x[0]], &[x[1]], &[x[2]]);
                    text.draw_3d(x[0], x[1], x[2], &txt);
                }
            }
        }
        plot.add(&curve);
        plot.add(&text);

        // done
        Ok(plot)
    }

    /// Calculates the key of the container where the point should fall in
    ///
    /// **Note:** Returns None if the point is out-of-range
    #[inline]
    fn calc_container_key(&self, x: &[f64]) -> Option<usize> {
        let mut ratio = vec![0; self.ndim]; // ratio = trunc(δx[i]/Δx[i]) (Eq. 8)
        let mut key = 0;
        for i in 0..self.ndim {
            if x[i] < self.xmin[i] || x[i] > self.xmax[i] {
                return None;
            }
            ratio[i] = ((x[i] - self.xmin[i]) / self.side_length[i]) as usize;
            if ratio[i] == self.ndiv[i] {
                // the point is exactly on the max edge, thus select inner container
                ratio[i] -= 1; // move to the inside
            }
            key += ratio[i] * self.coefficient[i];
        }
        Some(key)
    }

    /// Computes the i,j,k indices of the lower-left-bottom corner of the container
    #[inline]
    fn container_pivot_indices(&self, key: usize) -> (usize, usize, usize) {
        let i = key % self.ndiv[0];
        let j = (key % self.coefficient[2]) / self.ndiv[0];
        let k = key / self.coefficient[2];
        (i, j, k)
    }

    /// Computes the center coordinates of container
    #[inline]
    fn container_center(&self, cen: &mut [f64], i: usize, j: usize, k: usize) {
        cen[0] = self.xmin[0] + (i as f64) * self.side_length[0] + self.side_length[0] / 2.0;
        cen[1] = self.xmin[1] + (j as f64) * self.side_length[1] + self.side_length[1] / 2.0;
        if self.ndim == 3 {
            cen[2] = self.xmin[2] + (k as f64) * self.side_length[2] + self.side_length[2] / 2.0;
        }
    }

    /// Returns the keys of containers near a line
    #[inline]
    fn containers_near_line(&self, a: &[f64], b: &[f64]) -> Result<Vec<usize>, StrError> {
        let mut nearest_containers = Vec::new();
        let mut cen = vec![0.0; self.ndim];
        for key in self.containers.keys() {
            // compute container center
            let (i, j, k) = self.container_pivot_indices(*key);
            self.container_center(&mut cen, i, j, k);
            // check if the center of container is near the segment
            let distance = point_line_distance(a, b, &cen)?;
            if distance <= self.radius + self.tol_dist {
                nearest_containers.push(*key);
            }
        }
        Ok(nearest_containers)
    }

    /// Returns the keys of containers near a circle
    #[inline]
    fn containers_near_circle(&self, circle_center: &[f64], radius: f64) -> Result<Vec<usize>, StrError> {
        let mut nearest_containers = Vec::new();
        let mut cen = vec![0.0; self.ndim];
        for key in self.containers.keys() {
            // compute container center
            let (i, j, k) = self.container_pivot_indices(*key);
            self.container_center(&mut cen, i, j, k);
            // check if the center of container is near the circle
            let distance = point_circle_distance(circle_center, radius, &cen)?;
            if distance <= self.radius + self.tol_dist {
                nearest_containers.push(*key);
            }
        }
        Ok(nearest_containers)
    }

    /// Returns the keys of containers near a circle
    #[inline]
    fn containers_near_cylinder(&self, a: &[f64], b: &[f64], radius: f64) -> Result<Vec<usize>, StrError> {
        let mut nearest_containers = Vec::new();
        let mut cen = vec![0.0; self.ndim];
        for key in self.containers.keys() {
            // compute container center
            let (i, j, k) = self.container_pivot_indices(*key);
            self.container_center(&mut cen, i, j, k);
            // check if the center of container is near the cylinder
            let distance = point_cylinder_distance(a, b, radius, &cen)?;
            if distance <= self.radius + self.tol_dist {
                nearest_containers.push(*key);
            }
        }
        Ok(nearest_containers)
    }

    /// Returns the keys of containers near plane xy
    #[inline]
    fn containers_near_plane(&self, fixed_dim: usize, fixed_coord: f64) -> Vec<usize> {
        let mut nearest_containers = Vec::new();
        let mut cen = vec![0.0; self.ndim];
        for key in self.containers.keys() {
            // compute container center
            let (i, j, k) = self.container_pivot_indices(*key);
            self.container_center(&mut cen, i, j, k);
            // check if the center of container is near the plane
            let distance = f64::abs(cen[fixed_dim] - fixed_coord);
            if distance <= self.radius + self.tol_dist {
                nearest_containers.push(*key);
            }
        }
        nearest_containers
    }

    /// Updates a container or inserts a point into an existing container
    ///
    /// Note: we need to store the coordinates for later use
    /// such as when calculating point-to-point distances
    #[inline]
    fn update_or_insert(&mut self, key: ContainerKey, id: ItemID, x: &[f64]) {
        let container = self.containers.entry(key).or_insert(HashMap::new());
        container.insert(id, x.to_vec());
    }

    /// Sets square/cubic halo around point
    #[inline]
    fn set_halo(&mut self, x: &[f64]) {
        if self.ndim == 2 {
            self.halo[0][0] = x[0] - self.tolerance;
            self.halo[0][1] = x[1] - self.tolerance;

            self.halo[1][0] = x[0] + self.tolerance;
            self.halo[1][1] = x[1] - self.tolerance;

            self.halo[2][0] = x[0] + self.tolerance;
            self.halo[2][1] = x[1] + self.tolerance;

            self.halo[3][0] = x[0] - self.tolerance;
            self.halo[3][1] = x[1] + self.tolerance;
        } else {
            self.halo[0][0] = x[0] - self.tolerance;
            self.halo[0][1] = x[1] - self.tolerance;
            self.halo[0][2] = x[2] - self.tolerance;

            self.halo[1][0] = x[0] + self.tolerance;
            self.halo[1][1] = x[1] - self.tolerance;
            self.halo[1][2] = x[2] - self.tolerance;

            self.halo[2][0] = x[0] + self.tolerance;
            self.halo[2][1] = x[1] + self.tolerance;
            self.halo[2][2] = x[2] - self.tolerance;

            self.halo[3][0] = x[0] - self.tolerance;
            self.halo[3][1] = x[1] + self.tolerance;
            self.halo[3][2] = x[2] - self.tolerance;

            self.halo[4][0] = x[0] - self.tolerance;
            self.halo[4][1] = x[1] - self.tolerance;
            self.halo[4][2] = x[2] + self.tolerance;

            self.halo[5][0] = x[0] + self.tolerance;
            self.halo[5][1] = x[1] - self.tolerance;
            self.halo[5][2] = x[2] + self.tolerance;

            self.halo[6][0] = x[0] + self.tolerance;
            self.halo[6][1] = x[1] + self.tolerance;
            self.halo[6][2] = x[2] + self.tolerance;

            self.halo[7][0] = x[0] - self.tolerance;
            self.halo[7][1] = x[1] + self.tolerance;
            self.halo[7][2] = x[2] + self.tolerance;
        }
    }
}

impl fmt::Display for GridSearch {
    /// Shows info about the items in the grid containers
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // items
        let mut unique_items: HashMap<usize, bool> = HashMap::new();
        let mut indices: Vec<_> = self.containers.keys().collect();
        indices.sort();
        for index in indices {
            let container = self.containers.get(index).unwrap();
            let mut ids: Vec<_> = container.keys().map(|id| *id).collect();
            ids.sort();
            write!(f, "{}: {:?}\n", index, ids).unwrap();
            for id in ids {
                unique_items.insert(id, true);
            }
        }
        // summary
        let mut ids: Vec<_> = unique_items.keys().collect();
        ids.sort();
        write!(f, "ids = {:?}\n", ids).unwrap();
        write!(f, "nitem = {}\n", unique_items.len()).unwrap();
        write!(f, "ncontainer = {}\n", self.containers.len()).unwrap();
        write!(f, "ndiv = {:?}\n", self.ndiv).unwrap();
        Ok(())
    }
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#[cfg(test)]
mod tests {

    /*
    use super::GridSearch;
    use crate::util::SQRT_2;
    use crate::StrError;
    use plotpy::{Canvas, Curve, Surface};
    use russell_chk::{assert_approx_eq, assert_vec_approx_eq};

    struct TestData<'a> {
        id: usize,
        x: &'a [f64],
        container: usize,        // container index calc with x only
        containers: &'a [usize], // container index calc with halo and x
    }

    fn get_test_grid_2d() -> Result<GridSearch, StrError> {
        GridSearch::new(&[-0.2, -0.2], &[0.8, 1.8], 0.0, GsNdiv::Spec(5, 5, 0), GsTol::Default)
    }

    fn get_test_grid_3d() -> Result<GridSearch, StrError> {
        GridSearch::new(
            &[-1.0, -1.0, -1.0],
            &[1.0, 1.0, 1.0],
            0.0,
            GsNdiv::Spec(3, 3, 3),
            GsTol::Default,
        )
    }

    fn get_test_data_2d<'a>() -> Vec<TestData<'a>> {
        vec![
            TestData {
                id: 100,
                x: &[0.0, 0.2],
                container: 6,
                containers: &[0, 1, 5, 6],
            },
            TestData {
                id: 200,
                x: &[0.2, 0.6000000000000001],
                container: 12,
                containers: &[6, 7, 11, 12],
            },
            TestData {
                id: 300,
                x: &[0.4, 1.0],
                // in this case, the ratio is:
                // 3.0000000000000004, 2.9999999999999996
                // thus, the point falls in #13 instead of #18
                container: 13,
                containers: &[12, 13, 17, 18],
            },
            TestData {
                id: 400,
                x: &[0.6, 1.4],
                // in this case, the ratio is:
                // 4, 3.9999999999999996
                // thus, the point falls in #19 instead of #24
                container: 19,
                containers: &[18, 19, 23, 24],
            },
            TestData {
                id: 500,
                x: &[0.8, 1.8],
                container: 24,
                containers: &[24],
            },
            TestData {
                id: 600,
                x: &[0.6, 0.0],
                container: 4,
                containers: &[3, 4], // will be on 3 twice
            },
            // circle @ (-0.2,1.8) radius 0.3
            TestData {
                id: 101,
                x: &[-0.2, 1.5],
                container: 20,
                containers: &[20],
            },
            TestData {
                id: 102,
                x: &[-0.2 + 0.3 * SQRT_2 / 2.0, 1.8 - 0.3 * SQRT_2 / 2.0],
                container: 21,
                containers: &[21],
            },
            TestData {
                id: 103,
                x: &[0.1, 1.8],
                container: 21,
                containers: &[21],
            },
        ]
    }

    fn get_test_data_3d<'a>() -> Vec<TestData<'a>> {
        const L: f64 = 2.0;
        vec![
            TestData {
                id: 100,
                x: &[-1.0, -1.0, -1.0],
                container: 0,
                containers: &[0],
            },
            TestData {
                id: 200,
                x: &[0.0, 0.0, 0.0],
                container: 13,
                containers: &[13],
            },
            TestData {
                id: 300,
                x: &[-1.0 + L * 2.0 / 3.0, -1.0 + L * 2.0 / 3.0, -1.0 + L * 2.0 / 3.0],
                container: 26,
                containers: &[13, 14, 16, 17, 22, 23, 25, 26],
            },
            TestData {
                id: 400,
                x: &[-1.0 + L * 2.0 / 3.0, -0.7, -0.7],
                container: 2,
                containers: &[1, 2], // will be on 1 four times
            },
            TestData {
                id: 500,
                x: &[0.75, -0.75, -0.75],
                container: 2,
                containers: &[2],
            },
            // cylinder with 0.4 radius parallel to y passing through (1,-1,-1) and (1,1,-1)
            TestData {
                id: 101,
                x: &[1.0 - 0.4, -1.0, -1.0],
                container: 2,
                containers: &[2],
            },
            TestData {
                id: 102,
                x: &[1.0 - 0.4 * SQRT_2 / 2.0, -1.0, -1.0 + 0.4 * SQRT_2 / 2.0],
                container: 2,
                containers: &[2],
            },
            TestData {
                id: 103,
                x: &[1.0, -1.0, -1.0 + 0.4],
                container: 2,
                containers: &[2],
            },
            TestData {
                id: 104,
                x: &[1.0 - 0.4, 0.75, -1.0],
                container: 8,
                containers: &[8],
            },
            TestData {
                id: 105,
                x: &[1.0 - 0.4 * SQRT_2 / 2.0, 0.75, -1.0 + 0.4 * SQRT_2 / 2.0],
                container: 8,
                containers: &[8],
            },
            TestData {
                id: 106,
                x: &[1.0, 0.75, -1.0 + 0.4],
                container: 8,
                containers: &[8],
            },
        ]
    }

    #[test]
    fn new_fails_on_wrong_input() -> Result<(), StrError> {
        assert_eq!(
            GridSearch::new(&[0.0], &[1.0, 1.0], 0.0, GsNdiv::Default, GsTol::Default).err(),
            Some("min.len() = ndim must be 2 or 3")
        );

        assert_eq!(
            GridSearch::new(&[0.0, 0.0], &[1.0], 0.0, GsNdiv::Default, GsTol::Default).err(),
            Some("max.len() must equal ndim = min.len()")
        );

        assert_eq!(
            GridSearch::new(&[0.0, 0.0], &[1.0, 1.0], 0.0, GsNdiv::Spec(0, 1, 1), GsTol::Default).err(),
            Some("ndiv must be ≥ 1")
        );
        assert_eq!(
            GridSearch::new(
                &[0.0, 0.0, 0.0],
                &[1.0, 1.0, 1.0],
                0.0,
                GsNdiv::Spec(1, 0, 1),
                GsTol::Default
            )
            .err(),
            Some("ndiv must be ≥ 1")
        );
        assert_eq!(
            GridSearch::new(
                &[0.0, 0.0, 0.0],
                &[1.0, 1.0, 1.0],
                0.0,
                GsNdiv::Spec(1, 1, 0),
                GsTol::Default
            )
            .err(),
            Some("ndiv must be ≥ 1")
        );

        assert_eq!(
            GridSearch::new(&[0.0, 0.0], &[0.0, 1.0], 0.0, GsNdiv::Spec(10, 10, 10), GsTol::Default).err(),
            Some("max must be greater than min")
        );

        assert_eq!(
            GridSearch::new(
                &[0.0, 0.0, 0.0],
                &[1.0, 0.0, 1.0],
                0.0,
                GsNdiv::Spec(10, 10, 10),
                GsTol::Default
            )
            .err(),
            Some("max must be greater than min")
        );
        assert_eq!(
            GridSearch::new(
                &[0.0, 0.0, 0.0],
                &[1.0, 1.0, 0.0],
                0.0,
                GsNdiv::Spec(10, 10, 10),
                GsTol::Default
            )
            .err(),
            Some("max must be greater than min")
        );

        assert_eq!(
            GridSearch::new(
                &[0.0, 0.0],
                &[1.0, 1.0],
                0.0,
                GsNdiv::Spec(100, 1, 1),
                GsTol::Spec(0.5 * (1.0 / 100.0), 1e-4, 1e-4)
            )
            .err(),
            Some("container size = (max-min)/ndiv must be > 2·tol; reduce ndiv or tol")
        );
        assert_eq!(
            GridSearch::new(
                &[0.0, 0.0, 0.0],
                &[1.0, 1.0, 1.0],
                0.0,
                GsNdiv::Spec(1, 100, 1),
                GsTol::Spec(1e-4, 0.5 * (1.0 / 100.0), 1e-4)
            )
            .err(),
            Some("container size = (max-min)/ndiv must be > 2·tol; reduce ndiv or tol")
        );
        assert_eq!(
            GridSearch::new(
                &[0.0, 0.0, 0.0],
                &[1.0, 1.0, 1.0],
                0.0,
                GsNdiv::Spec(1, 1, 100),
                GsTol::Spec(1e-4, 1e-4, 0.5 * (1.0 / 100.0))
            )
            .err(),
            Some("container size = (max-min)/ndiv must be > 2·tol; reduce ndiv or tol")
        );
        Ok(())
    }

    #[test]
    fn new_works() -> Result<(), StrError> {
        let g2d = GridSearch::new(
            &[0.0, 0.0],
            &[10.0, 1.0],
            0.0,
            GsNdiv::Prop(20),
            GsTol::Spec(1e-4, 1e-5, 0.0),
        )?;
        assert_eq!(g2d.ndiv, [20, 2]);
        assert_eq!(g2d.tol, [1e-4, 1e-5]);

        let g3d = GridSearch::new(
            &[0.0, 0.0, 0.0],
            &[10.0, 1.0, 20.0],
            0.0,
            GsNdiv::Prop(20),
            GsTol::Spec(1e-4, 1e-5, 1e-6),
        )?;
        assert_eq!(g3d.ndiv, [10, 2, 20]);
        assert_eq!(g3d.tol, [1e-4, 1e-5, 1e-6]);

        let g2d = get_test_grid_2d()?;
        assert_eq!(g2d.ndim, 2);
        assert_eq!(g2d.ndiv, [5, 5]);
        assert_eq!(g2d.xmin, [-0.2, -0.2]);
        assert_eq!(g2d.xmax, [0.8, 1.8]);
        assert_eq!(g2d.xdelta, [1.0, 2.0]);
        assert_eq!(g2d.side_length, [0.2, 0.4]);
        assert_eq!(g2d.coefficient, [1, 5, 25]);
        assert_eq!(g2d.tol, [1e-4, 1e-4]);
        assert_eq!(g2d.halo.len(), 4);
        assert_eq!(g2d.halo_ncorner, 4);
        assert_eq!(g2d.containers.len(), 0);
        assert_approx_eq!(g2d.radius, f64::sqrt(0.1 * 0.1 + 0.2 * 0.2), 1e-15);
        assert_approx_eq!(g2d.tol_dist, f64::sqrt(2.0 * 1e-4 * 1e-4), 1e-15);

        let g3d = get_test_grid_3d()?;
        assert_eq!(g3d.ndim, 3);
        assert_eq!(g3d.ndiv, [3, 3, 3]);
        assert_eq!(g3d.xmin, [-1.0, -1.0, -1.0]);
        assert_eq!(g3d.xmax, [1.0, 1.0, 1.0]);
        assert_eq!(g3d.xdelta, [2.0, 2.0, 2.0]);
        assert_eq!(g3d.side_length, [2.0 / 3.0, 2.0 / 3.0, 2.0 / 3.0]);
        assert_eq!(g3d.coefficient, [1, 3, 9]);
        assert_eq!(g3d.tol, [1e-4, 1e-4, 1e-4]);
        assert_eq!(g3d.halo.len(), 8);
        assert_eq!(g3d.halo_ncorner, 8);
        assert_eq!(g3d.containers.len(), 0);
        assert_approx_eq!(g3d.radius, f64::sqrt(3.0 * (1.0 / 3.0) * (1.0 / 3.0)), 1e-15);
        assert_approx_eq!(g3d.tol_dist, f64::sqrt(3.0 * 1e-4 * 1e-4), 1e-15);
        Ok(())
    }

    #[test]
    fn display_trait_works() -> Result<(), StrError> {
        let g2d = get_test_grid_2d()?;
        assert_eq!(
            format!("{}", g2d),
            "ids = []\n\
             nitem = 0\n\
             ncontainer = 0\n\
             ndiv = [5, 5]\n"
        );

        let g3d = get_test_grid_3d()?;
        assert_eq!(
            format!("{}", g3d),
            "ids = []\n\
             nitem = 0\n\
             ncontainer = 0\n\
             ndiv = [3, 3, 3]\n"
        );
        Ok(())
    }

    #[test]
    fn draw_works_2d() -> Result<(), StrError> {
        let mut grid = get_test_grid_2d()?;
        for data in get_test_data_2d() {
            grid.insert(data.id, data.x)?;
        }
        let mut plot = grid.draw()?;
        if false {
            let mut canvas = Canvas::new();
            canvas.set_face_color("None").set_edge_color("magenta");
            canvas.draw_circle(0.5, 0.8, grid.radius);
            canvas.draw_circle(0.1, 0.4, grid.radius);
            canvas.draw_circle(0.5, 0.0, grid.radius);
            canvas.draw_circle(0.1, 1.6, grid.radius);
            canvas.set_edge_color("#fab32f").set_line_width(1.5);
            canvas.draw_polyline(&vec![vec![0.6, -0.2], vec![0.6, 1.8]], false);
            canvas.draw_polyline(&vec![vec![-0.2, 1.8], vec![0.8, 1.8]], false);
            canvas.draw_polyline(&vec![vec![0.2, -0.2], vec![0.8, 0.1]], false);
            canvas.draw_polyline(
                &vec![vec![0.1 + grid.radius, -0.2], vec![0.1 + grid.radius, 1.8]],
                false,
            );
            canvas.set_edge_color("green").set_line_width(0.5);
            canvas.draw_circle(-0.2, 1.8, 0.3);
            plot.add(&canvas);
            plot.set_equal_axes(true)
                .set_range(-0.4, 1.0, -0.4, 2.0)
                .set_ticks_x(0.1, 0.0, "")
                .set_num_ticks_y(12)
                .grid_and_labels("x", "y")
                .set_figure_size_points(400.0, 800.0);
            plot.save("/tmp/gemlab/test_plot_grid_search_2d.svg")?;
        }
        Ok(())
    }

    #[test]
    fn draw_works_3d() -> Result<(), StrError> {
        let mut grid = get_test_grid_3d()?;
        for data in get_test_data_3d() {
            grid.insert(data.id, data.x)?;
        }
        let mut plot = grid.draw()?;
        if false {
            let mut curve = Curve::new();
            curve.set_line_color("#fab32f").set_line_width(1.5);
            curve.draw_3d(&[-1.0, 1.0], &[-1.0, -1.0], &[-1.0, -1.0]);
            curve.draw_3d(&[-1.0, 1.0], &[-1.0, 1.0], &[-1.0, 1.0]);
            let mut surface = Surface::new();
            surface.set_with_surface(false).set_with_wireframe(true);
            surface.draw_cylinder(&[1.0, -1.0, -1.0], &[1.0, 1.0, -1.0], 0.4, 1, 20)?;
            plot.add(&curve);
            plot.add(&surface);
            plot.set_figure_size_points(600.0, 600.0);
            plot.save("/tmp/gemlab/test_plot_grid_search_3d.svg")?;
        }
        Ok(())
    }

    #[test]
    fn set_halo_works() -> Result<(), StrError> {
        let mut g2d = get_test_grid_2d()?;
        g2d.set_halo(&[0.5, 0.5]);
        assert_eq!(g2d.halo[0], [0.4999, 0.4999]);
        assert_eq!(g2d.halo[1], [0.5001, 0.4999]);
        assert_eq!(g2d.halo[2], [0.5001, 0.5001]);
        assert_eq!(g2d.halo[3], [0.4999, 0.5001]);

        let mut g3d = get_test_grid_3d()?;
        g3d.set_halo(&[0.5, 0.5, 0.5]);
        assert_eq!(g3d.halo[0], [0.4999, 0.4999, 0.4999]);
        assert_eq!(g3d.halo[1], [0.5001, 0.4999, 0.4999]);
        assert_eq!(g3d.halo[2], [0.5001, 0.5001, 0.4999]);
        assert_eq!(g3d.halo[3], [0.4999, 0.5001, 0.4999]);
        assert_eq!(g3d.halo[4], [0.4999, 0.4999, 0.5001]);
        assert_eq!(g3d.halo[5], [0.5001, 0.4999, 0.5001]);
        assert_eq!(g3d.halo[6], [0.5001, 0.5001, 0.5001]);
        assert_eq!(g3d.halo[7], [0.4999, 0.5001, 0.5001]);
        Ok(())
    }

    #[test]
    fn container_index_works() -> Result<(), StrError> {
        let g2d = get_test_grid_2d()?;
        for data in get_test_data_2d() {
            let index = g2d.calc_container_key(data.x);
            assert_eq!(index, Some(data.container));
        }
        // outside, to the left
        assert_eq!(g2d.calc_container_key(&[-10.0, 0.0]), None);
        // outside, to the right
        assert_eq!(g2d.calc_container_key(&[0.80001, 0.0]), None);
        // outside, to the bottom
        assert_eq!(g2d.calc_container_key(&[0.0, -1.0]), None);
        // outside, to the top
        assert_eq!(g2d.calc_container_key(&[0.0, 2.0]), None);
        // outside, to the bottom-left
        assert_eq!(g2d.calc_container_key(&[-100.0, -100.0]), None);
        // outside, to the top-right
        assert_eq!(g2d.calc_container_key(&[100.0, 100.0]), None);

        let g3d = get_test_grid_3d()?;
        for data in get_test_data_3d() {
            let index = g3d.calc_container_key(data.x);
            assert_eq!(index, Some(data.container));
        }
        assert_eq!(g3d.calc_container_key(&[1.00001, 0.0, 0.0]), None);
        assert_eq!(g3d.calc_container_key(&[0.0, 1.00001, 0.0]), None);
        assert_eq!(g3d.calc_container_key(&[0.0, 0.0, 1.00001]), None);
        assert_eq!(g3d.calc_container_key(&[-10.0, -10.0, -10.0]), None);
        assert_eq!(g3d.calc_container_key(&[10.0, -10.0, -10.0]), None);
        assert_eq!(g3d.calc_container_key(&[-10.0, 10.0, -10.0]), None);
        assert_eq!(g3d.calc_container_key(&[10.0, 10.0, -10.0]), None);
        assert_eq!(g3d.calc_container_key(&[-10.0, -10.0, 10.0]), None);
        assert_eq!(g3d.calc_container_key(&[10.0, -10.0, 10.0]), None);
        assert_eq!(g3d.calc_container_key(&[-10.0, 10.0, 10.0]), None);
        assert_eq!(g3d.calc_container_key(&[10.0, 10.0, 10.0]), None);
        Ok(())
    }

    #[test]
    fn container_index_handles_imprecision() -> Result<(), StrError> {
        let grid = GridSearch::new(
            &[6.123233995736766e-17, 0.0],
            &[2.0000001, 2.0],
            0.0,
            GsNdiv::Default,
            GsTol::Default,
        )?;
        if false {
            let mut plot = grid.draw()?;
            plot.set_equal_axes(true)
                .set_figure_size_points(800.0, 800.0)
                .save("/tmp/gemlab/test_container_index_handles_imprecision.svg")?;
        }
        assert_eq!(grid.calc_container_key(&[0.0, 0.0]), None);
        assert_eq!(grid.calc_container_key(&[2.0, 0.0]), Some(19));
        assert_eq!(grid.calc_container_key(&[2.0, 2.0]), Some(379));
        assert_eq!(grid.calc_container_key(&[0.0, 2.0]), None);

        let grid = GridSearch::new(
            &[6.123233995736766e-17, 0.0],
            &[2.0000001, 2.0],
            0.01,
            GsNdiv::Default,
            GsTol::Default,
        )?;
        assert_eq!(grid.calc_container_key(&[0.0, 0.0]), Some(0));
        assert_eq!(grid.calc_container_key(&[2.0, 0.0]), Some(19));
        assert_eq!(grid.calc_container_key(&[2.0, 2.0]), Some(379));
        assert_eq!(grid.calc_container_key(&[0.0, 2.0]), Some(360));
        Ok(())
    }

    #[test]
    fn container_pivot_indices_works() -> Result<(), StrError> {
        let g2d = get_test_grid_2d()?;
        assert_eq!(g2d.container_pivot_indices(0), (0, 0, 0));
        assert_eq!(g2d.container_pivot_indices(4), (4, 0, 0));
        assert_eq!(g2d.container_pivot_indices(20), (0, 4, 0));
        assert_eq!(g2d.container_pivot_indices(24), (4, 4, 0));
        assert_eq!(g2d.container_pivot_indices(8), (3, 1, 0));
        assert_eq!(g2d.container_pivot_indices(17), (2, 3, 0));
        assert_eq!(g2d.container_pivot_indices(23), (3, 4, 0));

        let g3d = get_test_grid_3d()?;
        assert_eq!(g3d.container_pivot_indices(0), (0, 0, 0));
        assert_eq!(g3d.container_pivot_indices(2), (2, 0, 0));
        assert_eq!(g3d.container_pivot_indices(6), (0, 2, 0));
        assert_eq!(g3d.container_pivot_indices(8), (2, 2, 0));
        assert_eq!(g3d.container_pivot_indices(18), (0, 0, 2));
        assert_eq!(g3d.container_pivot_indices(20), (2, 0, 2));
        assert_eq!(g3d.container_pivot_indices(24), (0, 2, 2));
        assert_eq!(g3d.container_pivot_indices(26), (2, 2, 2));
        assert_eq!(g3d.container_pivot_indices(13), (1, 1, 1));
        Ok(())
    }

    #[test]
    fn container_center_works() -> Result<(), StrError> {
        let g2d = get_test_grid_2d()?;
        let mut cen2d = vec![0.0; 2];
        g2d.container_center(&mut cen2d, 0, 0, 0);
        assert_vec_approx_eq!(cen2d, &[-0.1, 0.0], 1e-15);
        g2d.container_center(&mut cen2d, 4, 0, 0);
        assert_vec_approx_eq!(cen2d, &[0.7, 0.0], 1e-15);
        g2d.container_center(&mut cen2d, 0, 4, 0);
        assert_vec_approx_eq!(cen2d, &[-0.1, 1.6], 1e-15);
        g2d.container_center(&mut cen2d, 4, 4, 0);
        assert_vec_approx_eq!(cen2d, &[0.7, 1.6], 1e-15);
        g2d.container_center(&mut cen2d, 3, 1, 0);
        assert_vec_approx_eq!(cen2d, &[0.5, 0.4], 1e-15);
        g2d.container_center(&mut cen2d, 2, 3, 0);
        assert_vec_approx_eq!(cen2d, &[0.3, 1.2], 1e-15);
        g2d.container_center(&mut cen2d, 3, 4, 0);
        assert_vec_approx_eq!(cen2d, &[0.5, 1.6], 1e-15);

        let g3d = get_test_grid_3d()?;
        let mut cen3d = vec![0.0; 3];
        let l = 2.0 / 3.0;
        let hl = l / 2.0;
        let l2 = l * 2.0;
        g3d.container_center(&mut cen3d, 0, 0, 0);
        assert_vec_approx_eq!(cen3d, &[-1.0 + hl, -1.0 + hl, -1.0 + hl], 1e-14);
        g3d.container_center(&mut cen3d, 2, 0, 0);
        assert_vec_approx_eq!(cen3d, &[-1.0 + l2 + hl, -1.0 + hl, -1.0 + hl], 1e-14);
        g3d.container_center(&mut cen3d, 0, 2, 0);
        assert_vec_approx_eq!(cen3d, &[-1.0 + hl, -1.0 + l2 + hl, -1.0 + hl], 1e-14);
        g3d.container_center(&mut cen3d, 2, 2, 2);
        assert_vec_approx_eq!(cen3d, &[-1.0 + l2 + hl, -1.0 + l2 + hl, -1.0 + l2 + hl], 1e-14);
        Ok(())
    }

    #[test]
    fn is_outside_works() -> Result<(), StrError> {
        let g2d = get_test_grid_2d()?;
        assert_eq!(g2d.is_outside(&[-0.3, 0.8]), true);
        assert_eq!(g2d.is_outside(&[0.3, -0.3]), true);
        assert_eq!(g2d.is_outside(&[0.3, 0.8]), false);

        let g3d = get_test_grid_3d()?;
        assert_eq!(g3d.is_outside(&[-1.1, 0.0, 0.0]), true);
        assert_eq!(g3d.is_outside(&[0.0, -1.1, 0.0]), true);
        assert_eq!(g3d.is_outside(&[0.0, 0.0, -1.1]), true);
        assert_eq!(g3d.is_outside(&[0.0, 0.0, 0.0]), false);
        Ok(())
    }

    #[test]
    fn insert_fails_on_wrong_input() -> Result<(), StrError> {
        let mut g2d = get_test_grid_2d()?;
        let res = g2d.insert(0, &[0.0, 0.0, 0.0]);
        assert_eq!(res, Err("x.len() must equal ndim"));
        let res = g2d.insert(1000, &[0.80001, 0.0]);
        assert_eq!(res, Err("cannot insert point outside the grid"));

        let mut g3d = get_test_grid_3d()?;
        let res = g3d.insert(0, &[0.0, 0.0]);
        assert_eq!(res, Err("x.len() must equal ndim"));
        let res = g3d.insert(1000, &[1.00001, 0.0, 0.0]);
        assert_eq!(res, Err("cannot insert point outside the grid"));
        Ok(())
    }

    #[test]
    fn insert_2d_works() -> Result<(), StrError> {
        let mut grid = get_test_grid_2d()?;
        for data in get_test_data_2d() {
            grid.insert(data.id, data.x)?;
            for index in data.containers {
                let container = grid.containers.get(index).unwrap();
                container.values().find(|item| item.id == data.id).unwrap();
            }
        }
        assert_eq!(
            format!("{}", grid),
            "0: [100]\n\
             1: [100]\n\
             3: [600]\n\
             4: [600]\n\
             5: [100]\n\
             6: [100, 200]\n\
             7: [200]\n\
             11: [200]\n\
             12: [200, 300]\n\
             13: [300]\n\
             17: [300]\n\
             18: [300, 400]\n\
             19: [400]\n\
             20: [101]\n\
             21: [102, 103]\n\
             23: [400]\n\
             24: [400, 500]\n\
             ids = [100, 101, 102, 103, 200, 300, 400, 500, 600]\n\
             nitem = 9\n\
             ncontainer = 17\n\
             ndiv = [5, 5]\n"
        );
        let mut indices: Vec<_> = grid.containers.into_keys().collect();
        indices.sort();
        assert_eq!(indices, &[0, 1, 3, 4, 5, 6, 7, 11, 12, 13, 17, 18, 19, 20, 21, 23, 24]);
        Ok(())
    }

    #[test]
    fn insert_2d_works_boundaries() -> Result<(), StrError> {
        let mut grid = GridSearch::new(&[0.0, 0.0], &[2.0, 1.0], 0.0, GsNdiv::Spec(2, 1, 0), GsTol::Default)?;
        grid.insert(0, &[0.0, 0.0])?;
        grid.insert(1, &[1.0, 0.0])?;
        grid.insert(2, &[1.0, 1.0])?;
        grid.insert(3, &[0.0, 1.0])?;
        grid.insert(4, &[2.0, 0.0])?;
        grid.insert(5, &[2.0, 1.0])?;
        assert_eq!(
            format!("{}", grid),
            "0: [0, 1, 2, 3]\n\
             1: [1, 2, 4, 5]\n\
             ids = [0, 1, 2, 3, 4, 5]\n\
             nitem = 6\n\
             ncontainer = 2\n\
             ndiv = [2, 1]\n"
        );
        Ok(())
    }

    #[test]
    fn insert_3d_works() -> Result<(), StrError> {
        let mut grid = get_test_grid_3d()?;
        for data in get_test_data_3d() {
            grid.insert(data.id, data.x)?;
            for index in data.containers {
                let container = grid.containers.get(index).unwrap();
                container.values().find(|item| item.id == data.id).unwrap();
            }
        }
        assert_eq!(
            format!("{}", grid),
            "0: [100]\n\
             1: [400]\n\
             2: [101, 102, 103, 400, 500]\n\
             8: [104, 105, 106]\n\
             13: [200, 300]\n\
             14: [300]\n\
             16: [300]\n\
             17: [300]\n\
             22: [300]\n\
             23: [300]\n\
             25: [300]\n\
             26: [300]\n\
             ids = [100, 101, 102, 103, 104, 105, 106, 200, 300, 400, 500]\n\
             nitem = 11\n\
             ncontainer = 12\n\
             ndiv = [3, 3, 3]\n"
        );
        let mut indices: Vec<_> = grid.containers.into_keys().collect();
        indices.sort();
        assert_eq!(indices, &[0, 1, 2, 8, 13, 14, 16, 17, 22, 23, 25, 26]);
        Ok(())
    }

    #[test]
    fn find_fails_on_wrong_input() -> Result<(), StrError> {
        let g2d = get_test_grid_2d()?;
        let res = g2d.find(&[0.0, 0.0, 0.0]);
        assert_eq!(res, Err("x.len() must equal ndim"));
        let res = g2d.find(&[0.80001, 0.0]);
        assert_eq!(res, Err("cannot find point because the coordinates are outside the grid"));

        let g3d = get_test_grid_3d()?;
        let res = g3d.find(&[0.0, 0.0]);
        assert_eq!(res, Err("x.len() must equal ndim"));
        let res = g3d.find(&[1.00001, 0.0, 0.0]);
        assert_eq!(res, Err("cannot find point because the coordinates are outside the grid"));
        Ok(())
    }

    #[test]
    fn find_works() -> Result<(), StrError> {
        let mut g2d = get_test_grid_2d()?;
        for data in get_test_data_2d() {
            g2d.insert(data.id, data.x)?;
            let id = g2d.find(data.x)?;
            assert_eq!(id, Some(data.id));
        }
        let id = g2d.find(&[0.5, 0.5])?;
        assert_eq!(id, None);

        let mut g3d = get_test_grid_3d()?;
        for data in get_test_data_3d() {
            g3d.insert(data.id, data.x)?;
            let id = g3d.find(data.x)?;
            assert_eq!(id, Some(data.id));
        }
        let id = g3d.find(&[0.5, 0.5, 0.5])?;
        assert_eq!(id, None);
        Ok(())
    }

    #[test]
    fn containers_near_line_2d_works() -> Result<(), StrError> {
        let mut g2d = get_test_grid_2d()?;
        for data in get_test_data_2d() {
            g2d.insert(data.id, data.x)?;
        }
        // vertical right-most
        let mut indices = g2d.containers_near_line(&[0.6, 0.0], &[0.6, 1.8])?;
        indices.sort();
        assert_eq!(indices, &[3, 4, 13, 18, 19, 23, 24]);

        // vertical middle
        let mut indices = g2d.containers_near_line(&[0.1 + g2d.radius, 0.0], &[0.1 + g2d.radius, 1.8])?;
        indices.sort();
        assert_eq!(indices, &[1, 3, 6, 7, 11, 12, 13, 17, 18, 21, 23]);

        // horizontal top-most
        let mut indices = g2d.containers_near_line(&[-0.2, 1.8], &[0.8, 1.8])?;
        indices.sort();
        assert_eq!(indices, &[20, 21, 23, 24]);

        // sloped
        let mut indices = g2d.containers_near_line(&[0.2, -0.2], &[0.8, 0.1])?;
        indices.sort();
        assert_eq!(indices, &[1, 3, 4]);
        Ok(())
    }

    #[test]
    fn containers_near_line_3d_works() -> Result<(), StrError> {
        let mut g3d = get_test_grid_3d()?;
        for data in get_test_data_3d() {
            g3d.insert(data.id, data.x)?;
        }
        let mut indices = g3d.containers_near_line(&[-1.0, -1.0, -1.0], &[1.0, -1.0, -1.0])?;
        indices.sort();
        assert_eq!(indices, &[0, 1, 2]);

        let mut indices = g3d.containers_near_line(&[-1.0, -1.0, -1.0], &[1.0, 1.0, 1.0])?;
        indices.sort();
        assert_eq!(indices, &[0, 1, 13, 14, 16, 17, 22, 23, 25, 26]);
        Ok(())
    }

    #[test]
    fn find_on_line_fails_on_wrong_input() -> Result<(), StrError> {
        let g2d = get_test_grid_2d()?;
        let res = g2d.find_on_line(&[0.0], &[1.0, 1.0]);
        assert_eq!(res, Err("a.len() must equal ndim"));
        let res = g2d.find_on_line(&[0.0, 0.0], &[1.0]);
        assert_eq!(res, Err("b.len() must equal ndim"));
        Ok(())
    }

    #[test]
    fn find_on_line_2d_works() -> Result<(), StrError> {
        let mut g2d = get_test_grid_2d()?;
        for data in get_test_data_2d() {
            g2d.insert(data.id, data.x)?;
        }
        // vertical right-most
        let map = g2d.find_on_line(&[0.6, 0.0], &[0.6, 1.8])?;
        let mut ids: Vec<_> = map.iter().collect();
        ids.sort();
        assert_eq!(ids, [&400, &600]);

        // vertical middle
        let map = g2d.find_on_line(&[0.1 + g2d.radius, 0.0], &[0.1 + g2d.radius, 1.8])?;
        let ids: Vec<_> = map.iter().collect();
        assert_eq!(ids.len(), 0);

        // horizontal top-most
        let map = g2d.find_on_line(&[-0.2, 1.8], &[0.8, 1.8])?;
        let mut ids: Vec<_> = map.iter().collect();
        ids.sort();
        assert_eq!(ids, [&103, &500]);

        // sloped
        let map = g2d.find_on_line(&[0.2, -0.2], &[0.8, 0.1])?;
        let mut ids: Vec<_> = map.iter().collect();
        ids.sort();
        assert_eq!(ids, [&600]);
        Ok(())
    }

    #[test]
    fn find_on_line_3d_works() -> Result<(), StrError> {
        let mut g3d = get_test_grid_3d()?;
        for data in get_test_data_3d() {
            g3d.insert(data.id, data.x)?;
        }
        let map = g3d.find_on_line(&[-1.0, -1.0, -1.0], &[1.0, -1.0, -1.0])?;
        let mut ids: Vec<_> = map.iter().collect();
        ids.sort();
        assert_eq!(ids, [&100, &101]);

        let map = g3d.find_on_line(&[-1.0, -1.0, -1.0], &[1.0, 1.0, 1.0])?;
        let mut ids: Vec<_> = map.iter().collect();
        ids.sort();
        assert_eq!(ids, [&100, &200, &300]);
        Ok(())
    }

    #[test]
    fn containers_near_circle_works() -> Result<(), StrError> {
        let mut g2d = get_test_grid_2d()?;
        for data in get_test_data_2d() {
            g2d.insert(data.id, data.x)?;
        }
        let mut indices = g2d.containers_near_circle(&[-0.2, 1.8], 0.3)?;
        indices.sort();
        assert_eq!(indices, &[20, 21]);
        Ok(())
    }

    #[test]
    fn find_on_circle_fails_on_wrong_input() -> Result<(), StrError> {
        let g2d = get_test_grid_2d()?;
        let res = g2d.find_on_circle(&[-0.2], 0.3);
        assert_eq!(res, Err("center.len() must equal ndim"));

        let g3d = get_test_grid_3d()?;
        let res = g3d.find_on_circle(&[0.0, 0.0, 0.0], 1.0);
        assert_eq!(res, Err("this works in 2D only"));
        Ok(())
    }

    #[test]
    fn find_on_circle_works() -> Result<(), StrError> {
        let mut g2d = get_test_grid_2d()?;
        for data in get_test_data_2d() {
            g2d.insert(data.id, data.x)?;
        }
        let map = g2d.find_on_circle(&[-0.2, 1.8], 0.3)?;
        let mut ids: Vec<_> = map.iter().collect();
        ids.sort();
        assert_eq!(ids, [&101, &102, &103]);
        Ok(())
    }

    #[test]
    fn containers_near_cylinder_works() -> Result<(), StrError> {
        let mut g3d = get_test_grid_3d()?;
        for data in get_test_data_3d() {
            g3d.insert(data.id, data.x)?;
        }
        let mut indices = g3d.containers_near_cylinder(&[1.0, -1.0, -1.0], &[1.0, 1.0, -1.0], 0.4)?;
        indices.sort();
        assert_eq!(indices, &[2, 8]);
        Ok(())
    }

    #[test]
    fn find_on_cylinder_fails_on_wrong_input() -> Result<(), StrError> {
        let g3d = get_test_grid_3d()?;
        let res = g3d.find_on_cylinder(&[0.0, 0.0], &[1.0, 0.0, 0.0], 1.0);
        assert_eq!(res, Err("a.len() must equal ndim"));
        let res = g3d.find_on_cylinder(&[0.0, 0.0, 0.0], &[1.0, 0.0], 1.0);
        assert_eq!(res, Err("b.len() must equal ndim"));

        let g2d = get_test_grid_2d()?;
        let res = g2d.find_on_cylinder(&[0.0, 0.0, 0.0], &[1.0, 0.0, 0.0], 1.0);
        assert_eq!(res, Err("this works in 3D only"));
        Ok(())
    }

    #[test]
    fn find_on_cylinder_works() -> Result<(), StrError> {
        let mut g3d = get_test_grid_3d()?;
        for data in get_test_data_3d() {
            g3d.insert(data.id, data.x)?;
        }
        let map = g3d.find_on_cylinder(&[1.0, -1.0, -1.0], &[1.0, 1.0, -1.0], 0.4)?;
        let mut ids: Vec<_> = map.iter().collect();
        ids.sort();
        assert_eq!(ids, [&101, &102, &103, &104, &105, &106]);
        Ok(())
    }

    #[test]
    fn containers_near_plane_works() -> Result<(), StrError> {
        let mut g3d = get_test_grid_3d()?;
        for data in get_test_data_3d() {
            g3d.insert(data.id, data.x)?;
        }
        let mut indices = g3d.containers_near_plane(0, -1.0);
        indices.sort();
        assert_eq!(indices, &[0]);

        let mut indices = g3d.containers_near_plane(1, -1.0);
        indices.sort();
        assert_eq!(indices, &[0, 1, 2]);

        let mut indices = g3d.containers_near_plane(2, -1.0);
        indices.sort();
        assert_eq!(indices, &[0, 1, 2, 8]);

        let mut indices = g3d.containers_near_plane(2, 0.0);
        indices.sort();
        assert_eq!(indices, &[13, 14, 16, 17]);
        Ok(())
    }

    #[test]
    fn find_on_plane_fails_on_wrong_input() -> Result<(), StrError> {
        let g2d = get_test_grid_2d()?;
        let res = g2d.find_on_plane_xy(-1.0);
        assert_eq!(res, Err("this works in 3D only"));

        let res = g2d.find_on_plane_yz(-1.0);
        assert_eq!(res, Err("this works in 3D only"));

        let res = g2d.find_on_plane_xz(-1.0);
        assert_eq!(res, Err("this works in 3D only"));
        Ok(())
    }

    #[test]
    fn find_on_plane_works() -> Result<(), StrError> {
        let mut g3d = get_test_grid_3d()?;
        for data in get_test_data_3d() {
            g3d.insert(data.id, data.x)?;
        }
        let map = g3d.find_on_plane_xy(-1.0)?;
        let mut ids: Vec<_> = map.iter().collect();
        ids.sort();
        assert_eq!(ids, [&100, &101, &104]);

        let map = g3d.find_on_plane_yz(-1.0)?;
        let mut ids: Vec<_> = map.iter().collect();
        ids.sort();
        assert_eq!(ids, [&100]);

        let map = g3d.find_on_plane_xz(-1.0)?;
        let mut ids: Vec<_> = map.iter().collect();
        ids.sort();
        assert_eq!(ids, [&100, &101, &102, &103]);
        Ok(())
    }

    #[test]
    fn maybe_insert_works() -> Result<(), StrError> {
        let mut grid = GridSearch::new(&[0.0, 0.0], &[1.0, 1.0], 0.0, GsNdiv::Spec(3, 3, 0), GsTol::Default)?;
        let id = grid.maybe_insert(111, &[0.5, 0.5])?;
        assert_eq!(id, 111);
        let id = grid.maybe_insert(222, &[0.75, 0.75])?;
        assert_eq!(id, 222);
        let id = grid.maybe_insert(333, &[0.5, 0.5])?;
        assert_eq!(id, 111); // existent
        Ok(())
    }
    */
}
